package Scoreboard;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class GameController {
    //@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    //private UserRepository userRepository;
    @Autowired GameService gameService;

    @GetMapping(path="/play") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (/*@RequestParam String name
            , @RequestParam String email*/) throws InterruptedException {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        /*Game n = new Game();
        n.setHomeTeamId(1);
        n.setAwayTeamId(2);
        n.setHomeScore(5);
        n.setAwayScore(0);
        System.out.println("CONTROLLER:"+userRepository);
        userRepository.save(n);
        return "SAVED in controller";
        GameService gameService = new GameService();*/

        return gameService.playGame(1, 2, Sport.HOCKEY, null);
    }

    /*@GetMapping(path="/all")
    public @ResponseBody Iterable<Game> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }*/
}